# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Lodjinha' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Lodjinha

  target 'LodjinhaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LodjinhaUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
